updated sample project
Laserfiche/lf-sample-repository-api-java pull request #5
Opened 2022-07-28 20:35 UTC by sxu1998

added everything in the sample project to mirror the js/c# sample projects
updated the readme file
still need to resolve some comments made earlier after the demo (will do that in another push)

2022-07-29 20:58 UTC, lf-jason-jia commented on src/main/java/sample/Sample.java
> +        String repoName = repoListResponse.join().get(0).getRepoName();
Please compose the async code instead of making it blocking here.
Again, it's fine for integration test, but not okay for educational purpose.

2022-07-29 20:59 UTC, lf-jason-jia commented on src/main/java/sample/Sample.java
> +        String repoId = repoListResponse.join().get(0).getRepoId();
Same here

2022-07-29 21:00 UTC, lf-jason-jia commented on src/main/java/sample/Sample.java
> +        String repoName = repoListResponse.join().get(0).getRepoName();
It seems a bit more understanding on CompletableFuture would be good. Could you go over some tutorial on how to write code with CompletableFuture?

2022-07-29 21:01 UTC, lf-jason-jia commented on src/main/java/sample/Sample.java
> +        return CompletableFuture.completedFuture(children);
Same here. If we already get blocked on line 46, what's the point of returning a CompletableFutrue<List<Entry>>?

2022-07-29 21:01 UTC, lf-jason-jia requested changes
Please learn CompletableFuture first and make changes.

2022-07-29 21:02 UTC, jason-chan-lf commented on src/main/java/sample/Sample.java
> +public class Sample {
Since the Sample.java file path was changed, the link to the sample code in the README should also be updated

2022-08-02 13:36 UTC, sxu1998 commented
> Please learn CompletableFuture first and make changes.

i thought you said that using the join() and get() method was ok last mob session but sure i can do some more research

2022-09-30 14:55 UTC, sxu1998 commented on src/main/java/sample/Sample.java
> +        String repoName = repoListResponse.join().get(0).getRepoName();
wrapped a `supplyAsync()` function around the blocking functions and a `thenAcceptAsync` function around the print statements

2022-09-30 15:42 UTC, jason-chan-lf commented on src/main/java/sample/Sample.java
> +    public static CompletableFuture<String> getRepoName() {
since this is a sample for people unfamiliar with the api, we should try to avoid abbreviations. I think `getRepositoryName` would be a more clear name for the function. 

Can you also update the other abbreviated variable names in the project? like ServiceConfig.spKey

2022-09-30 15:42 UTC, jason-chan-lf commented on src/main/java/sample/Sample.java
> +    private static RepositoryApiClient client = createRepoApiClient();
If users try to read what the sample project is doing, maybe it would be misleading that the RepositoryApiClient is created as a static variable up here outside of the main function. Do you think it would be more clear to call `createRepoApiClient()` in the main function?

2022-09-30 16:11 UTC, jason-chan-lf approved these changes, later dismissed
I verified that i was able to follow the readme instructions and could run the sample project. I'll let @lf-jason-jia review the CompletableFuture since i'm not familiar with this

2022-09-30 20:38 UTC, lf-jason-jia commented on src/main/java/sample/Sample.java
> +        String repositoryName = getRepositoryName().join();
Do you remember the mob we had a few days ago where Paolo mentioned we could do chaininig of CompletableFuture? We could do it here instead of three (`repositoryName`, `rootFolder`, `rootFolderChildren`) blocking calls.

2022-09-30 20:41 UTC, lf-jason-jia requested changes
Hmm, still the old suggestion, please learn how to use CompletableFuture properly :open_book:. Here is a good tutorial I found: https://www.baeldung.com/java-completablefuture

2022-09-30 20:48 UTC, lf-jason-jia requested changes

2022-09-30 20:48 UTC, lf-jason-jia commented on src/main/java/sample/Sample.java
> +                repositoryListResponse.join().get(0).getRepoName());
This is not proper use of CompletableFuture. The code works, has not build error, but it's not correct. Here is why:

1. Please read about the use case of `supplyAsync`.
2. After 1, we could realize that line 29 is anti pattern becasue the whole point of `supplyAsync` is to turn a blocking operation into an async one at the cost of extra thread usage. Now, you already have a async operation `repositoryListResponse` but you joined it to make it blocking and then use `supplyAsync` to offset its effect. This just doesn't make sense.

2022-09-30 20:48 UTC, lf-jason-jia commented on src/main/java/sample/Sample.java
> +                repositoryListResponse.join().get(0).getRepoId());
Similar to the above comment

2022-09-30 20:49 UTC, lf-jason-jia commented on src/main/java/sample/Sample.java
> +            System.out.println("Repository Name: " + repositoryIdAsync);
In isolation, this use case is correct.

2022-09-30 20:50 UTC, lf-jason-jia commented on src/main/java/sample/Sample.java
> +        CompletableFuture<Entry> entry = entryResponse.supplyAsync(() ->
Same, you turn an async operation into blocking and use `supplyAsync` to make it again async.

2022-09-30 20:50 UTC, lf-jason-jia commented on src/main/java/sample/Sample.java
> +        CompletableFuture<String> rootFolderName = entry.supplyAsync(() -> entry.join().getName());
Same, turning async into blocking and back into async, plus wasting one extra thread.

2022-09-30 20:51 UTC, lf-jason-jia commented on src/main/java/sample/Sample.java
> +            if (rootFolderNameAsync.length() == 0) {
This usage is fine.

2022-09-30 20:51 UTC, lf-jason-jia commented on src/main/java/sample/Sample.java
> +        CompletableFuture<List<Entry>> children = folderChildren.supplyAsync(() -> folderChildren.join().getValue());
Same, making async blocking and back to async with one thread wasted.

2022-09-30 20:53 UTC, lf-jason-jia commented on src/main/java/sample/Sample.java
> +                System.out.println(i++ + ":[" + child.getEntryType() + " id:" + child.getId() + "] " + "'" + child.getName() + "'");
Could probably use `printf` to make it simpler.

2022-09-30 22:39 UTC, sxu1998 commented on src/main/java/sample/Sample.java
> +                repositoryListResponse.join().get(0).getRepoName());
ok so i got rid of all the blocking functions except for the 3 in the main function, not really sure how to chain them (but still get them to execute each function)

2022-10-03 15:19 UTC, lf-jason-jia commented on src/main/java/sample/Sample.java
> +                repositoryListResponse.join().get(0).getRepoName());
Please take a look at this link: https://www.baeldung.com/java-completablefuture as for how to chain two CompletableFuture.

2022-10-04 15:54 UTC, lf-jason-jia commented on .gitignore
>  *.env
Shall we remove this one?

2022-10-04 15:55 UTC, lf-jason-jia commented on src/main/java/sample/Sample.java
> +        CompletableFuture<String> repositoryName = repositoryListResponse.thenApplyAsync(repositoryInfos -> repositoryInfos.get(0).getRepoName());
I think since we don't have a thread bool for the executor, we should use `thenApply` instead.

2022-10-04 15:55 UTC, lf-jason-jia commented on src/main/java/sample/Sample.java
> +        CompletableFuture<String> repositoryName = repositoryListResponse.thenApplyAsync(repositoryInfos -> repositoryInfos.get(0).getRepoName());
The same for other occurences.

2022-10-04 17:17 UTC, lf-jason-jia approved these changes

2022-10-04 17:18 UTC, merged